apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
     {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
       {{- toYaml . | nindent 8 }}
     {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: {{ printf "%s-master:%.0f" .Values.redis.fullnameOverride .Values.redis.master.service.port }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
